splashTxt = [
    "Also try Minecraft",
    "Also try Terraria",
    "Also try Battleship",
    "Made without Unreal",
    "Made without Unity",
    "I wanna work with Godot",
    "I am bored",
    "Rooooooobert",
    "Rochen ist ein Aal",
    "Unmöglich ist ein starker Gegner",
    "Was ist denn mit Carsten los?",
    "Nett hier, aber haben sie schon Hobbylos mit 5 Sternen bewertet?",
    "Nett hier, aber waren sie schon mal in Baden Württemberg",
    "Hier gibt es nichts zu sehen",
    "Wer wo dass list isd doff",
    "Wo ist das Mehl hin?",
    "Gottloses Glatteis hier",
    "Putze deine Zaehne!",
    "Fischige Situation",
    "Fischerverschenken",
    "Smells fishy",
    "Oh Henry...",
    "Stay Hydrated",
    "Toller Hecht!",
    'Try pressing "m"',
    "Fishy on me",
    "Fischers Fritze",
    "Wie tief ist das Wasser?",
    "Amogus",
    "Also try MC Kart",
    "Sub to Skyblock Squad",
    "Sub to xJanise",
    "Sub to Kyucy",
    "Wololo",
    "Bruh",
    "Sheesh",
    "xD",
    "Cam haz fish",
    "Grauenvoll",
    "Was? Nein!",
    "Nein? Doch! Oh!",
    "Mein, Dein, das sind doch bürgerliche Kategorien",
    "Schanke dön!",
    "Sehr liebenswuerzig!",
    "Das kann doch nicht Warzenschwein!",
    "We got cookies",
    "C'mon I have candy...",
    "Geschickt eingeschaedelt",
    "Das ist ein Splashtext",
    "*Hier könnte Ihre Werbung stehen*",
    "Splish Splash",
    "Still water?",
    "Reicht für Frankreich",
    "Dieses Projekt ist ins Wasser gefallen",
    "Witze am laufenden Band",
    "de.splash.example.witz",
    "_placeholder_",
    "Ich will nicht mehr...",
    "Wann ist Feierabend?",
    "Danke, Thorsten!",
    "Hast du schon deine Essensmarke?",
    "Warum liegt hier Stroh?",
    "What does the fox say?",
    "Ding ding ding ding",
    "I am your father (maybe)",
    "Roll for initative",
    "missing ; on line 69",
    "Never gonna give you up",
    "Never gonna let you down",
    "fischeversenken.py",
    "Hallo, Herr Fischer!",
    "Hallo, Herr Scholz!",
    "Guck mal, Mama! Ich bin im Splashtext!",
    "Powered by Regensteiner (Spritzig)",
    "Powered by coffein",
    "Ende Splashtexte",
    "Sponsored by Raubzugschattenlegenden",
    "Managed by Idiotenzentrum",
    "Corny?",
    "Warum funktioniert das nicht?",
    "Warum crasht es?",
    "Jetzt mit 50% weniger Kaefern! (Hoffentlich)",
    "20%"+" auf alles, auser Tiernahrung",
    "Bitte helfen Sie mir",
    "Es wird Suppe gegessen!",
    "Jetzt, ohne Parkkantiene!",
    "Legga, Bommes",
    "NSFT",
    "Safe for work",
    "Bitte spiel mit mir :(",
    "Die haben mich hier eingesperrt!",
    "Therapeuten hassen diesen Trick.",
    "invalid value",
    "index out of range",
    "Heute ist ein guter Tag!",
    "Wer hat dir das erlaubt?",
    "Jaahaa!",
    "Das weis man",
    "...---...",
    "Das macht Sinn",
    "Das ergibt Sinn",
    "Das produziert Sinn",
    "Wann gutes Internet?",
    "Yaahoo",
    "hihi",
    "Eine Kampfespartei!",
    "(._____.)",
    "Hai, Fisch!",
    "Was wollen wir Thun, Fisch?",
    "Du hast die Wal, Fisch.",
    "Da bin ich Platt, Fisch.",
    "Jetzt auch geraeuchert.",
    "Schuesse bei die Fische",
    "Und wir schauen mal, was passiert.",
    "Raviolicode",
    "Also add some protein",
    "That's a lot of damage!",
    "OK boomer",
    "Alle Wale ausgerottet!",
    "Shader fertig geladen!",
    "Aktualisiere: 12,6%",
    "Nicht boese gemeint!",
    "Du geiler Fang, du! ;)",
    "Nice fish, __init__(self)?",
    "Sponsored bei Norden Virtuelles Privates Netzwerk",
    "powered by ritalin",
    "Le Fishe au chocolat",
    "Knapp daneben ist auch vorbei",
    "20 Euro Paypal und dann joa",
    "a²^2 + b²^2 = c²^2",
    "Koko kokkoko? Koko kokko.",
    "Alt + F4 und die Welt gehoert dir",
    "Hoch die Haende, Wochenende",
    "Es ist Mittwoch, meine Kerle",
    "/gamemode 1",
    "Ich werd's Ihnen lohnen im spaeteren Leben! Einsweilen, besten Dank!",
    "Aua!",
    "Diese Splashtext ist sehr sehr lang, da fehlt noch ein r, dieser Splashtext ist wirklich sehr, hoer auf mit zu schreiben, lass es!",
    "Es gibt mehr als 2 Splashtexte",
    "Es gibt über 500 Splashtexte",
    "Es gibt 18+ Splashtexte",
    "Dieser Text ist falsch!",
    "Dynamitisch Programmiert",
    "Jetzt mit ueberspringbarem Ladebalken",
    "^^",
    "Q war hier",
    "awarded for a game of a year",
    "ein Spiel um Leben oder Lebkuchen"
    "Rewe Spekulatius 4 ever",
    "so war das nicht gemeint",
    "frohes Schaffen",
    "das war's auch schon wieder",
    "all my homies hate JavaScript",
    "Ryzen > AMD",
    "tobb Sigrid",
    "Aales klar",
    "Puffer(Fisch) enthalten"
]